stage1_bootloader:
	$(TARGET_ASM) $(TARGET_STAGE1_ASMFLAGS) -o $(BUILD_DIR)/$(BOOTLOADER_STAGE1_BIN) $(BOOTLOADER_STAGE1)/BOOT.asm

clean_stage1_bootloader:
	rm -f $(BUILD_DIR)/$(BOOTLOADER_STAGE1_BIN)